package webserver

type Config struct {
	ListenAddress string `yaml:"listenAddress"`

	// TLS enables HTTPS and secure WebSockets when present.
	TLS *ConfigTLS `yaml:"tls,omitempty"`

	// Auth lists credentials accepted by every API endpoint.
	Auth []ConfigAuth `yaml:"auth,omitempty"`
}

// ConfigTLS identifies the certificate and private key presented by the
// Salmon webserver.
type ConfigTLS struct {
	// CertFile is the path to the PEM-encoded server certificate chain.
	CertFile string `yaml:"certFile"`

	// KeyFile is the path to the PEM-encoded private key for CertFile.
	KeyFile string `yaml:"keyFile"`
}

// ConfigAuth identifies one accepted client credential. Exactly one
// authentication method must be configured.
type ConfigAuth struct {
	// ID identifies this credential in configuration and logs.
	ID string `yaml:"id"`

	// BearerTokenHash is the SHA-256 hash generated by salmon-watch.
	BearerTokenHash string `yaml:"bearerTokenHash,omitempty"`
}
